name: Node.js CI

on:
  push:
    branches: [ "fő-" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Kód letöltése
        uses: actions/checkout@v4

      - name: Node.js beállítása
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Függőségek telepítése
        run: npm ci

      - name: Tesztek futtatása
        run: npm test

      - name: Bejelentkezés a GitHub Container Registry-be
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker image buildelése és pusholása GHCR-be
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/hello-devops:latest
