name: Node.js CI

on:
  push:
    branches: [ "fő-" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Kód letöltése
        uses: actions/checkout@v4

      - name: Node.js beállítása
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Függőségek telepítése
        run: npm ci

      - name: Tesztek futtatása
        run: npm test
